// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file oauthapp/v1/token.proto (package oauthapp.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTokenInfoRequest, GetTokenInfoResponse, GetTokenRequest, GetTokenResponse } from "./token_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service oauthapp.v1.TokeService
 */
export const TokeService = {
  typeName: "oauthapp.v1.TokeService",
  methods: {
    /**
     * @generated from rpc oauthapp.v1.TokeService.GetToken
     */
    getToken: {
      name: "GetToken",
      I: GetTokenRequest,
      O: GetTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc oauthapp.v1.TokeService.GetTokenInfo
     */
    getTokenInfo: {
      name: "GetTokenInfo",
      I: GetTokenInfoRequest,
      O: GetTokenInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

