// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file grpcoauth/v1/enums.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file grpcoauth/v1/enums.proto.
 */
export const file_grpcoauth_v1_enums: GenFile = /*@__PURE__*/
  fileDesc("ChhncnBjb2F1dGgvdjEvZW51bXMucHJvdG8SDGdycGNvYXV0aC52MSpoCglHcmFudFR5cGUSGgoWR1JBTlRfVFlQRV9VTlNQRUNJRklFRBAAEiEKHUdSQU5UX1RZUEVfQVVUSE9SSVpBVElPTl9DT0RFEAESHAoYR1JBTlRfVFlQRV9SRUZSRVNIX1RPS0VOEAIqTgoIUm9sZVR5cGUSGQoVUk9MRV9UWVBFX1VOU1BFQ0lGSUVEEAASEwoPUk9MRV9UWVBFX0FETUlOEAESEgoOUk9MRV9UWVBFX1VTRVIQAipgCgxSZXNwb25zZVR5cGUSHQoZUkVTUE9OU0VfVFlQRV9VTlNQRUNJRklFRBAAEhkKFVJFU1BPTlNFX1RZUEVfU1VDQ0VTUxABEhYKElJFU1BPTlNFX1RZUEVfRkFJTBACKmoKCUxvZ2luVHlwZRIaChZMT0dJTl9UWVBFX1VOU1BFQ0lGSUVEEAASFQoRTE9HSU5fVFlQRV9OQVRJVkUQARIUChBMT0dJTl9UWVBFX0tBS0FPEAISFAoQTE9HSU5fVFlQRV9OQVZFUhADKj4KCVRva2VuVHlwZRIaChZUT0tFTl9UWVBFX1VOU1BFQ0lGSUVEEAASFQoRVE9LRU5fVFlQRV9CRUFSRVIQAUKrAQoQY29tLmdycGNvYXV0aC52MUIKRW51bXNQcm90b1ABWjpnaXRodWIuY29tL3ZldDFtZW50cy9ncnBjb2F1dGgvZ28vZ3JwY29hdXRoL3YxO2dycGNvYXV0aHYxogIDR1hYqgIMR3JwY29hdXRoLlYxygIMR3JwY29hdXRoXFYx4gIYR3JwY29hdXRoXFYxXEdQQk1ldGFkYXRh6gINR3JwY29hdXRoOjpWMWIGcHJvdG8z");

/**
 * @generated from enum grpcoauth.v1.GrantType
 */
export enum GrantType {
  /**
   * 기본값wef
   *
   * @generated from enum value: GRANT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GRANT_TYPE_AUTHORIZATION_CODE = 1;
   */
  AUTHORIZATION_CODE = 1,

  /**
   * @generated from enum value: GRANT_TYPE_REFRESH_TOKEN = 2;
   */
  REFRESH_TOKEN = 2,
}

/**
 * Describes the enum grpcoauth.v1.GrantType.
 */
export const GrantTypeSchema: GenEnum<GrantType> = /*@__PURE__*/
  enumDesc(file_grpcoauth_v1_enums, 0);

/**
 * @generated from enum grpcoauth.v1.RoleType
 */
export enum RoleType {
  /**
   * @generated from enum value: ROLE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_TYPE_ADMIN = 1;
   */
  ADMIN = 1,

  /**
   * @generated from enum value: ROLE_TYPE_USER = 2;
   */
  USER = 2,
}

/**
 * Describes the enum grpcoauth.v1.RoleType.
 */
export const RoleTypeSchema: GenEnum<RoleType> = /*@__PURE__*/
  enumDesc(file_grpcoauth_v1_enums, 1);

/**
 * @generated from enum grpcoauth.v1.ResponseType
 */
export enum ResponseType {
  /**
   * @generated from enum value: RESPONSE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RESPONSE_TYPE_SUCCESS = 1;
   */
  SUCCESS = 1,

  /**
   * @generated from enum value: RESPONSE_TYPE_FAIL = 2;
   */
  FAIL = 2,
}

/**
 * Describes the enum grpcoauth.v1.ResponseType.
 */
export const ResponseTypeSchema: GenEnum<ResponseType> = /*@__PURE__*/
  enumDesc(file_grpcoauth_v1_enums, 2);

/**
 * @generated from enum grpcoauth.v1.LoginType
 */
export enum LoginType {
  /**
   * @generated from enum value: LOGIN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOGIN_TYPE_NATIVE = 1;
   */
  NATIVE = 1,

  /**
   * @generated from enum value: LOGIN_TYPE_KAKAO = 2;
   */
  KAKAO = 2,

  /**
   * @generated from enum value: LOGIN_TYPE_NAVER = 3;
   */
  NAVER = 3,
}

/**
 * Describes the enum grpcoauth.v1.LoginType.
 */
export const LoginTypeSchema: GenEnum<LoginType> = /*@__PURE__*/
  enumDesc(file_grpcoauth_v1_enums, 3);

/**
 * @generated from enum grpcoauth.v1.TokenType
 */
export enum TokenType {
  /**
   * @generated from enum value: TOKEN_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TOKEN_TYPE_BEARER = 1;
   */
  BEARER = 1,
}

/**
 * Describes the enum grpcoauth.v1.TokenType.
 */
export const TokenTypeSchema: GenEnum<TokenType> = /*@__PURE__*/
  enumDesc(file_grpcoauth_v1_enums, 4);

