// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file grpcoauth/v1/oauth.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { RoleType } from "./enums_pb";
import { file_grpcoauth_v1_enums } from "./enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grpcoauth/v1/oauth.proto.
 */
export const file_grpcoauth_v1_oauth: GenFile = /*@__PURE__*/
  fileDesc("ChhncnBjb2F1dGgvdjEvb2F1dGgucHJvdG8SDGdycGNvYXV0aC52MSJgCghPYXV0aEFwcBIkCgRyb2xlGAEgASgOMhYuZ3JwY29hdXRoLnYxLlJvbGVUeXBlEgoKAmlkGAIgASgJEgwKBG5hbWUYAyABKAkSFAoMcmVkaXJlY3RfdXJpGAQgASgJIooBCg9HZXRUb2tlblJlcXVlc3QSEgoKZ3JhbnRfdHlwZRgBIAEoCRIRCgljbGllbnRfaWQYAiABKAkSFAoMcmVkaXJlY3RfdXJpGAMgASgJEgwKBGNvZGUYBCABKAkSFQoNY2xpZW50X3NlY3JldBgFIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAYgASgJIpgBChBHZXRUb2tlblJlc3BvbnNlEhIKCnRva2VuX3R5cGUYASABKAkSFAoMYWNjZXNzX3Rva2VuGAIgASgJEhIKCmV4cGlyZXNfaW4YAyABKAMSFQoNcmVmcmVzaF90b2tlbhgEIAEoCRIgChhyZWZyZXNoX3Rva2VuX2V4cGlyZXNfaW4YBSABKAMSDQoFc2NvcGUYBiADKAkiaAoXR2V0QXV0aG9yaXplQ29kZVJlcXVlc3QSEQoJY2xpZW50X2lkGAEgASgJEhQKDHJlZGlyZWN0X3VyaRgCIAEoCRIVCg1yZXNwb25zZV90eXBlGAMgASgJEg0KBXN0YXRlGAQgASgJIjcKGEdldEF1dGhvcml6ZUNvZGVSZXNwb25zZRIMCgRjb2RlGAEgASgJEg0KBXN0YXRlGAIgASgJIi4KD0NhbGxiYWNrUmVxdWVzdBIMCgRjb2RlGAEgASgJEg0KBXN0YXRlGAIgASgJMvABCg1PYXV0aDJTZXJ2aWNlEnsKEEdldEF1dGhvcml6ZUNvZGUSJS5ncnBjb2F1dGgudjEuR2V0QXV0aG9yaXplQ29kZVJlcXVlc3QaJi5ncnBjb2F1dGgudjEuR2V0QXV0aG9yaXplQ29kZVJlc3BvbnNlIhiC0+STAhISEC9vYXV0aC9hdXRob3JpemUSYgoIR2V0VG9rZW4SHS5ncnBjb2F1dGgudjEuR2V0VG9rZW5SZXF1ZXN0Gh4uZ3JwY29hdXRoLnYxLkdldFRva2VuUmVzcG9uc2UiF4LT5JMCEToBKiIML29hdXRoL3Rva2VuMm4KFE9hdXRoQ2FsbGJhY2tTZXJ2aWNlElYKCENhbGxiYWNrEh0uZ3JwY29hdXRoLnYxLkNhbGxiYWNrUmVxdWVzdBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSITgtPkkwINEgsvY2FsbGJhY2svKkKrAQoQY29tLmdycGNvYXV0aC52MUIKT2F1dGhQcm90b1ABWjpnaXRodWIuY29tL3ZldDFtZW50cy9ncnBjb2F1dGgvZ28vZ3JwY29hdXRoL3YxO2dycGNvYXV0aHYxogIDR1hYqgIMR3JwY29hdXRoLlYxygIMR3JwY29hdXRoXFYx4gIYR3JwY29hdXRoXFYxXEdQQk1ldGFkYXRh6gINR3JwY29hdXRoOjpWMWIGcHJvdG8z", [file_google_api_annotations, file_google_protobuf_empty, file_grpcoauth_v1_enums]);

/**
 * @generated from message grpcoauth.v1.OauthApp
 */
export type OauthApp = Message<"grpcoauth.v1.OauthApp"> & {
  /**
   * @generated from field: grpcoauth.v1.RoleType role = 1;
   */
  role: RoleType;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string redirect_uri = 4;
   */
  redirectUri: string;
};

/**
 * Describes the message grpcoauth.v1.OauthApp.
 * Use `create(OauthAppSchema)` to create a new message.
 */
export const OauthAppSchema: GenMessage<OauthApp> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 0);

/**
 * @generated from message grpcoauth.v1.GetTokenRequest
 */
export type GetTokenRequest = Message<"grpcoauth.v1.GetTokenRequest"> & {
  /**
   *  grpcoauth.v1.GrantType grant_type = 1;fwewwer
   *
   * @generated from field: string grant_type = 1;
   */
  grantType: string;

  /**
   * @generated from field: string client_id = 2;
   */
  clientId: string;

  /**
   * @generated from field: string redirect_uri = 3;
   */
  redirectUri: string;

  /**
   * @generated from field: string code = 4;
   */
  code: string;

  /**
   * @generated from field: string client_secret = 5;
   */
  clientSecret: string;

  /**
   * @generated from field: string refresh_token = 6;
   */
  refreshToken: string;
};

/**
 * Describes the message grpcoauth.v1.GetTokenRequest.
 * Use `create(GetTokenRequestSchema)` to create a new message.
 */
export const GetTokenRequestSchema: GenMessage<GetTokenRequest> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 1);

/**
 * @generated from message grpcoauth.v1.GetTokenResponse
 */
export type GetTokenResponse = Message<"grpcoauth.v1.GetTokenResponse"> & {
  /**
   * @generated from field: string token_type = 1;
   */
  tokenType: string;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * @generated from field: int64 expires_in = 3;
   */
  expiresIn: bigint;

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;

  /**
   * @generated from field: int64 refresh_token_expires_in = 5;
   */
  refreshTokenExpiresIn: bigint;

  /**
   * @generated from field: repeated string scope = 6;
   */
  scope: string[];
};

/**
 * Describes the message grpcoauth.v1.GetTokenResponse.
 * Use `create(GetTokenResponseSchema)` to create a new message.
 */
export const GetTokenResponseSchema: GenMessage<GetTokenResponse> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 2);

/**
 * @generated from message grpcoauth.v1.GetAuthorizeCodeRequest
 */
export type GetAuthorizeCodeRequest = Message<"grpcoauth.v1.GetAuthorizeCodeRequest"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string redirect_uri = 2;
   */
  redirectUri: string;

  /**
   * @generated from field: string response_type = 3;
   */
  responseType: string;

  /**
   * @generated from field: string state = 4;
   */
  state: string;
};

/**
 * Describes the message grpcoauth.v1.GetAuthorizeCodeRequest.
 * Use `create(GetAuthorizeCodeRequestSchema)` to create a new message.
 */
export const GetAuthorizeCodeRequestSchema: GenMessage<GetAuthorizeCodeRequest> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 3);

/**
 * @generated from message grpcoauth.v1.GetAuthorizeCodeResponse
 */
export type GetAuthorizeCodeResponse = Message<"grpcoauth.v1.GetAuthorizeCodeResponse"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;
};

/**
 * Describes the message grpcoauth.v1.GetAuthorizeCodeResponse.
 * Use `create(GetAuthorizeCodeResponseSchema)` to create a new message.
 */
export const GetAuthorizeCodeResponseSchema: GenMessage<GetAuthorizeCodeResponse> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 4);

/**
 * @generated from message grpcoauth.v1.CallbackRequest
 */
export type CallbackRequest = Message<"grpcoauth.v1.CallbackRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;
};

/**
 * Describes the message grpcoauth.v1.CallbackRequest.
 * Use `create(CallbackRequestSchema)` to create a new message.
 */
export const CallbackRequestSchema: GenMessage<CallbackRequest> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_oauth, 5);

/**
 * @generated from service grpcoauth.v1.Oauth2Service
 */
export const Oauth2Service: GenService<{
  /**
   * @generated from rpc grpcoauth.v1.Oauth2Service.GetAuthorizeCode
   */
  getAuthorizeCode: {
    methodKind: "unary";
    input: typeof GetAuthorizeCodeRequestSchema;
    output: typeof GetAuthorizeCodeResponseSchema;
  },
  /**
   * @generated from rpc grpcoauth.v1.Oauth2Service.GetToken
   */
  getToken: {
    methodKind: "unary";
    input: typeof GetTokenRequestSchema;
    output: typeof GetTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_grpcoauth_v1_oauth, 0);

/**
 * @generated from service grpcoauth.v1.OauthCallbackService
 */
export const OauthCallbackService: GenService<{
  /**
   * @generated from rpc grpcoauth.v1.OauthCallbackService.Callback
   */
  callback: {
    methodKind: "unary";
    input: typeof CallbackRequestSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_grpcoauth_v1_oauth, 1);

