// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file grpcoauth/v1/oauth.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CallbackRequest, GetAuthorizeCodeRequest, GetAuthorizeCodeResponse, GetTokenRequest, GetTokenResponse } from "./oauth_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service grpcoauth.v1.Oauth2Service
 */
export const Oauth2Service = {
  typeName: "grpcoauth.v1.Oauth2Service",
  methods: {
    /**
     * @generated from rpc grpcoauth.v1.Oauth2Service.GetAuthorizeCode
     */
    getAuthorizeCode: {
      name: "GetAuthorizeCode",
      I: GetAuthorizeCodeRequest,
      O: GetAuthorizeCodeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.Oauth2Service.GetToken
     */
    getToken: {
      name: "GetToken",
      I: GetTokenRequest,
      O: GetTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service grpcoauth.v1.OauthCallbackService
 */
export const OauthCallbackService = {
  typeName: "grpcoauth.v1.OauthCallbackService",
  methods: {
    /**
     * @generated from rpc grpcoauth.v1.OauthCallbackService.Callback
     */
    callback: {
      name: "Callback",
      I: CallbackRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

