/**
 * @fileoverview gRPC-Web generated client stub for grpcoauth.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: grpcoauth/v1/oauth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as grpcoauth_v1_oauth_pb from '../../grpcoauth/v1/oauth_pb'; // proto import: "grpcoauth/v1/oauth.proto"


export class Oauth2ServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAuthorizeCode = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.Oauth2Service/GetAuthorizeCode',
    grpcWeb.MethodType.UNARY,
    grpcoauth_v1_oauth_pb.GetAuthorizeCodeRequest,
    grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse,
    (request: grpcoauth_v1_oauth_pb.GetAuthorizeCodeRequest) => {
      return request.serializeBinary();
    },
    grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse.deserializeBinary
  );

  getAuthorizeCode(
    request: grpcoauth_v1_oauth_pb.GetAuthorizeCodeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse>;

  getAuthorizeCode(
    request: grpcoauth_v1_oauth_pb.GetAuthorizeCodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse) => void): grpcWeb.ClientReadableStream<grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse>;

  getAuthorizeCode(
    request: grpcoauth_v1_oauth_pb.GetAuthorizeCodeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_oauth_pb.GetAuthorizeCodeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.Oauth2Service/GetAuthorizeCode',
        request,
        metadata || {},
        this.methodDescriptorGetAuthorizeCode,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.Oauth2Service/GetAuthorizeCode',
    request,
    metadata || {},
    this.methodDescriptorGetAuthorizeCode);
  }

  methodDescriptorGetToken = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.Oauth2Service/GetToken',
    grpcWeb.MethodType.UNARY,
    grpcoauth_v1_oauth_pb.GetTokenRequest,
    grpcoauth_v1_oauth_pb.GetTokenResponse,
    (request: grpcoauth_v1_oauth_pb.GetTokenRequest) => {
      return request.serializeBinary();
    },
    grpcoauth_v1_oauth_pb.GetTokenResponse.deserializeBinary
  );

  getToken(
    request: grpcoauth_v1_oauth_pb.GetTokenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<grpcoauth_v1_oauth_pb.GetTokenResponse>;

  getToken(
    request: grpcoauth_v1_oauth_pb.GetTokenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_oauth_pb.GetTokenResponse) => void): grpcWeb.ClientReadableStream<grpcoauth_v1_oauth_pb.GetTokenResponse>;

  getToken(
    request: grpcoauth_v1_oauth_pb.GetTokenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_oauth_pb.GetTokenResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.Oauth2Service/GetToken',
        request,
        metadata || {},
        this.methodDescriptorGetToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.Oauth2Service/GetToken',
    request,
    metadata || {},
    this.methodDescriptorGetToken);
  }

}

export class OauthCallbackServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCallback = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.OauthCallbackService/Callback',
    grpcWeb.MethodType.UNARY,
    grpcoauth_v1_oauth_pb.CallbackRequest,
    google_protobuf_empty_pb.Empty,
    (request: grpcoauth_v1_oauth_pb.CallbackRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  callback(
    request: grpcoauth_v1_oauth_pb.CallbackRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  callback(
    request: grpcoauth_v1_oauth_pb.CallbackRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  callback(
    request: grpcoauth_v1_oauth_pb.CallbackRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.OauthCallbackService/Callback',
        request,
        metadata || {},
        this.methodDescriptorCallback,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.OauthCallbackService/Callback',
    request,
    metadata || {},
    this.methodDescriptorCallback);
  }

}

