// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file grpcoauth/v1/user.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { GetAccessTokenInfoResponse, GetUserMeResponse, UserLogoutResponse } from "./user_pb.js";

/**
 * @generated from service grpcoauth.v1.UserService
 */
export const UserService = {
  typeName: "grpcoauth.v1.UserService",
  methods: {
    /**
     * @generated from rpc grpcoauth.v1.UserService.GetAccessTokenInfo
     */
    getAccessTokenInfo: {
      name: "GetAccessTokenInfo",
      I: Empty,
      O: GetAccessTokenInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.UserService.GetUserMe
     */
    getUserMe: {
      name: "GetUserMe",
      I: Empty,
      O: GetUserMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc grpcoauth.v1.UserService.UserLogout
     */
    userLogout: {
      name: "UserLogout",
      I: Empty,
      O: UserLogoutResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

