// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file grpcoauth/v1/user.proto (package grpcoauth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file grpcoauth/v1/user.proto.
 */
export const file_grpcoauth_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChdncnBjb2F1dGgvdjEvdXNlci5wcm90bxIMZ3JwY29hdXRoLnYxIqQBCgRVc2VyEiEKAmlkGAEgASgJQhW6SBJyEDIOXlthLXowLTldezI0fSQSFwoEbmFtZRgCIAEoCUIJukgGcgQQAhgUEjIKDHBob25lX251bWJlchgDIAEoCUIcukgZchcyFV4wMTBbMC05XXs0fVswLTldezR9JBIZCghuaWNrbmFtZRgEIAEoCUIHukgEcgIYFBIRCgl0aHVtYm5haWwYBSABKAkiFAoEdGVzdBIMCgR0ZXN0GAUgASgJIkwKGkdldEFjY2Vzc1Rva2VuSW5mb1Jlc3BvbnNlEgoKAmlkGAEgASgJEhIKCmV4cGlyZXNfaW4YAiABKAMSDgoGYXBwX2lkGAMgASgJIlUKEUdldFVzZXJNZVJlc3BvbnNlEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFAoMcGhvbmVfbnVtYmVyGAMgASgJEhAKCG5pY2tuYW1lGAQgASgJIiAKElVzZXJMb2dvdXRSZXNwb25zZRIKCgJpZBgBIAEoCTK8AgoLVXNlclNlcnZpY2USdwoSR2V0QWNjZXNzVG9rZW5JbmZvEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiguZ3JwY29hdXRoLnYxLkdldEFjY2Vzc1Rva2VuSW5mb1Jlc3BvbnNlIh+C0+STAhkSFy91c2VyL2FjY2Vzc190b2tlbl9pbmZvElYKCUdldFVzZXJNZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRofLmdycGNvYXV0aC52MS5HZXRVc2VyTWVSZXNwb25zZSIQgtPkkwIKEggvdXNlci9tZRJcCgpVc2VyTG9nb3V0EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiAuZ3JwY29hdXRoLnYxLlVzZXJMb2dvdXRSZXNwb25zZSIUgtPkkwIOEgwvdXNlci9sb2dvdXRCqgEKEGNvbS5ncnBjb2F1dGgudjFCCVVzZXJQcm90b1ABWjpnaXRodWIuY29tL3ZldDFtZW50cy9ncnBjb2F1dGgvZ28vZ3JwY29hdXRoL3YxO2dycGNvYXV0aHYxogIDR1hYqgIMR3JwY29hdXRoLlYxygIMR3JwY29hdXRoXFYx4gIYR3JwY29hdXRoXFYxXEdQQk1ldGFkYXRh6gINR3JwY29hdXRoOjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_google_api_annotations, file_google_protobuf_empty]);

/**
 * @generated from message grpcoauth.v1.User
 */
export type User = Message<"grpcoauth.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * we
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string phone_number = 3;
   */
  phoneNumber: string;

  /**
   * @generated from field: string nickname = 4;
   */
  nickname: string;

  /**
   * @generated from field: string thumbnail = 5;
   */
  thumbnail: string;
};

/**
 * Describes the message grpcoauth.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_user, 0);

/**
 * @generated from message grpcoauth.v1.test
 */
export type test = Message<"grpcoauth.v1.test"> & {
  /**
   * @generated from field: string test = 5;
   */
  test: string;
};

/**
 * Describes the message grpcoauth.v1.test.
 * Use `create(testSchema)` to create a new message.
 */
export const testSchema: GenMessage<test> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_user, 1);

/**
 * @generated from message grpcoauth.v1.GetAccessTokenInfoResponse
 */
export type GetAccessTokenInfoResponse = Message<"grpcoauth.v1.GetAccessTokenInfoResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: int64 expires_in = 2;
   */
  expiresIn: bigint;

  /**
   * @generated from field: string app_id = 3;
   */
  appId: string;
};

/**
 * Describes the message grpcoauth.v1.GetAccessTokenInfoResponse.
 * Use `create(GetAccessTokenInfoResponseSchema)` to create a new message.
 */
export const GetAccessTokenInfoResponseSchema: GenMessage<GetAccessTokenInfoResponse> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_user, 2);

/**
 * @generated from message grpcoauth.v1.GetUserMeResponse
 */
export type GetUserMeResponse = Message<"grpcoauth.v1.GetUserMeResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string phone_number = 3;
   */
  phoneNumber: string;

  /**
   * @generated from field: string nickname = 4;
   */
  nickname: string;
};

/**
 * Describes the message grpcoauth.v1.GetUserMeResponse.
 * Use `create(GetUserMeResponseSchema)` to create a new message.
 */
export const GetUserMeResponseSchema: GenMessage<GetUserMeResponse> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_user, 3);

/**
 * @generated from message grpcoauth.v1.UserLogoutResponse
 */
export type UserLogoutResponse = Message<"grpcoauth.v1.UserLogoutResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message grpcoauth.v1.UserLogoutResponse.
 * Use `create(UserLogoutResponseSchema)` to create a new message.
 */
export const UserLogoutResponseSchema: GenMessage<UserLogoutResponse> = /*@__PURE__*/
  messageDesc(file_grpcoauth_v1_user, 4);

/**
 * @generated from service grpcoauth.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc grpcoauth.v1.UserService.GetAccessTokenInfo
   */
  getAccessTokenInfo: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetAccessTokenInfoResponseSchema;
  },
  /**
   * @generated from rpc grpcoauth.v1.UserService.GetUserMe
   */
  getUserMe: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetUserMeResponseSchema;
  },
  /**
   * @generated from rpc grpcoauth.v1.UserService.UserLogout
   */
  userLogout: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof UserLogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_grpcoauth_v1_user, 0);

