/**
 * @fileoverview gRPC-Web generated client stub for grpcoauth.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: grpcoauth/v1/user.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as grpcoauth_v1_user_pb from '../../grpcoauth/v1/user_pb'; // proto import: "grpcoauth/v1/user.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAccessTokenInfo = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.UserService/GetAccessTokenInfo',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    grpcoauth_v1_user_pb.GetAccessTokenInfoResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    grpcoauth_v1_user_pb.GetAccessTokenInfoResponse.deserializeBinary
  );

  getAccessTokenInfo(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<grpcoauth_v1_user_pb.GetAccessTokenInfoResponse>;

  getAccessTokenInfo(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.GetAccessTokenInfoResponse) => void): grpcWeb.ClientReadableStream<grpcoauth_v1_user_pb.GetAccessTokenInfoResponse>;

  getAccessTokenInfo(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.GetAccessTokenInfoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.UserService/GetAccessTokenInfo',
        request,
        metadata || {},
        this.methodDescriptorGetAccessTokenInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.UserService/GetAccessTokenInfo',
    request,
    metadata || {},
    this.methodDescriptorGetAccessTokenInfo);
  }

  methodDescriptorGetUserMe = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.UserService/GetUserMe',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    grpcoauth_v1_user_pb.GetUserMeResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    grpcoauth_v1_user_pb.GetUserMeResponse.deserializeBinary
  );

  getUserMe(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<grpcoauth_v1_user_pb.GetUserMeResponse>;

  getUserMe(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.GetUserMeResponse) => void): grpcWeb.ClientReadableStream<grpcoauth_v1_user_pb.GetUserMeResponse>;

  getUserMe(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.GetUserMeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.UserService/GetUserMe',
        request,
        metadata || {},
        this.methodDescriptorGetUserMe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.UserService/GetUserMe',
    request,
    metadata || {},
    this.methodDescriptorGetUserMe);
  }

  methodDescriptorUserLogout = new grpcWeb.MethodDescriptor(
    '/grpcoauth.v1.UserService/UserLogout',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    grpcoauth_v1_user_pb.UserLogoutResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    grpcoauth_v1_user_pb.UserLogoutResponse.deserializeBinary
  );

  userLogout(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<grpcoauth_v1_user_pb.UserLogoutResponse>;

  userLogout(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.UserLogoutResponse) => void): grpcWeb.ClientReadableStream<grpcoauth_v1_user_pb.UserLogoutResponse>;

  userLogout(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: grpcoauth_v1_user_pb.UserLogoutResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpcoauth.v1.UserService/UserLogout',
        request,
        metadata || {},
        this.methodDescriptorUserLogout,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpcoauth.v1.UserService/UserLogout',
    request,
    metadata || {},
    this.methodDescriptorUserLogout);
  }

}

